FROM node:20.9.0-alpine AS student-prod

# Set environment variables
ARG NODE_ENV=production
ARG DATABASE_HOST=postgres_db
ARG DATABASE_PORT=5432
ARG DATABASE_USERNAME=postgres
ARG DATABASE_PASSWORD=123456
ARG DATABASE_NAME=rampup_students

# Set NODE_ENV in the container
ENV NODE_ENV=${NODE_ENV}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_USERNAME=${DATABASE_USERNAME}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_NAME=${DATABASE_NAME}


WORKDIR /usr/src/app


RUN npm -v
RUN npm install -g npm@10.1.0


COPY package.json ./


RUN npm install --only=production
RUN rm -f package.json

