FROM gateway-base:latest AS build

WORKDIR /usr/src/app

COPY . .

RUN npm run build

FROM gateway-prod AS prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist

RUN chown node:node -R /usr/src/app

USER node
EXPOSE 3000

CMD [ "node", "dist/main" ]