FROM node:20.9.0-alpine AS gateway-prod

# Set environment variables
ARG NODE_ENV=production

# Set NODE_ENV in the container
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app


RUN npm -v
RUN npm install -g npm@10.1.0


COPY package.json ./


RUN npm install --force --only=production
RUN rm -f package.json

