FROM node:20.9.0-alpine AS file-upload-prod

ARG REDIS_HOST=redis-cache
ARG REDIS_PORT=6379
ARG GRAPHQL_GATEWAY=http://student-service:3001/graphql

ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV GRAPHQL_GATEWAY=${GRAPHQL_GATEWAY}


WORKDIR /usr/src/app


RUN npm -v
RUN npm install -g npm@10.1.0


COPY package.json ./


RUN npm install --force --only=production
RUN rm -f package.json

