FROM file-upload-base:latest AS build

WORKDIR /usr/src/app

COPY . .

RUN npm run build

FROM file-upload-prod AS prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist

RUN chown node:node -R /usr/src/app

USER node

CMD [ "node", "dist/main" ]