FROM dashboard-base AS build

WORKDIR /usr/src/app

COPY . .

RUN npm install -g @angular/cli

RUN ng build --configuration=production

FROM dashboard-prod AS prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist

RUN npm install -g serve
EXPOSE 4200

CMD ["serve", "-s", "dist", "-l", "4200"]
